name: offlinemaps_release_automation
description: Reproducible GitHub Actions automation for EasyElevation map packs.
publish_to: none
version: 1.2.0+1

environment:
  sdk: '>=3.12.2 <3.13.0'

dependencies:
  crypto: 3.0.7
  path: 1.9.1

dev_dependencies:
  lints: 6.1.0
  test: 1.31.2
